# Generated by Django 4.2.7 on 2026-02-27 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(blank=True, choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], max_length=20, null=True)),
                ('technologies', models.JSONField(blank=True, null=True)),
                ('questions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, choices=[('aptitude', 'Aptitude'), ('technical', 'Technical'), ('mixed', 'Mixed')], max_length=20, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_banks',
                'indexes': [models.Index(fields=['level'], name='question_ba_level_84b93c_idx'), models.Index(fields=['is_active'], name='question_ba_is_acti_3bad5b_idx')],
            },
        ),
    ]
