# Generated by Django 4.2.7 on 2026-02-27 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTemplate',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], max_length=20, null=True)),
                ('technologies', models.JSONField(blank=True, null=True)),
                ('num_aptitude', models.IntegerField(default=5)),
                ('num_technical_per_tech', models.IntegerField(default=10)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('pass_percentage', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test_templates',
                'indexes': [models.Index(fields=['experience_level'], name='test_templa_experie_2a4737_idx'), models.Index(fields=['is_active'], name='test_templa_is_acti_495b58_idx')],
            },
        ),
    ]
