# Generated by Django 4.1.13 on 2026-03-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtemplate',
            name='candidate_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
