# Generated by Django 4.1.13 on 2026-03-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_templates', '0002_testtemplate_candidate_by_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtemplate',
            name='marks_per_aptitude',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testtemplate',
            name='marks_per_technical',
            field=models.IntegerField(default=1),
        ),
    ]
