# Generated by Django 4.1.13 on 2026-03-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_templates', '0003_testtemplate_marks_per_aptitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtemplate',
            name='candidate_by_email',
        ),
        migrations.RemoveField(
            model_name='testtemplate',
            name='marks_per_aptitude',
        ),
        migrations.RemoveField(
            model_name='testtemplate',
            name='marks_per_technical',
        ),
    ]
