# Generated by Django 4.2.7 on 2026-02-27 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='questions.category')),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'db_table': 'technologies',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('level', models.CharField(blank=True, choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('aptitude', 'Aptitude'), ('technical', 'Technical')], max_length=20, null=True)),
                ('technology', models.CharField(blank=True, max_length=100, null=True)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.IntegerField(blank=True, null=True)),
                ('marks', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('times_used', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank')], default='multiple_choice', max_length=20)),
                ('time_to_solve_seconds', models.IntegerField(default=60)),
                ('language', models.CharField(choices=[('english', 'English'), ('tamil', 'Tamil'), ('hindi', 'Hindi')], default='english', max_length=20)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'questions',
                'indexes': [models.Index(fields=['level'], name='questions_level_4db504_idx'), models.Index(fields=['technology'], name='questions_technol_5d4670_idx'), models.Index(fields=['category'], name='questions_categor_3ee678_idx'), models.Index(fields=['is_active'], name='questions_is_acti_ba6b3c_idx')],
            },
        ),
    ]
