# Generated by Django 4.2.7 on 2026-02-27 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('test_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('experience_level', models.CharField(max_length=20)),
                ('selected_technologies', models.JSONField(blank=True, null=True)),
                ('aptitude_questions', models.JSONField(default=list)),
                ('technical_questions', models.JSONField(default=dict)),
                ('answers', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('total_marks', models.IntegerField(default=0)),
                ('obtained_marks', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(db_column='candidate', on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(db_column='template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_templates.testtemplate')),
            ],
            options={
                'db_table': 'tests',
                'indexes': [models.Index(fields=['test_id'], name='tests_test_id_96d3a1_idx'), models.Index(fields=['candidate'], name='tests_candida_6dfb44_idx'), models.Index(fields=['status'], name='tests_status_7b792f_idx'), models.Index(fields=['-created_at'], name='tests_created_9ba3cd_idx')],
            },
        ),
    ]
